
package ru.ilia.soap.impls;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import ru.ilia.soap.service.CustomError;
import ru.service_shop.Price;
import ru.service_shop.PriceList;
import ru.service_shop.PriceListRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicePrice", targetNamespace = "http://service.soap.ilia.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ru.service_shop.ObjectFactory.class,
    ru.ilia.soap.service.ObjectFactory.class
})
public interface ServicePrice {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.soap.ilia.ru/ServicePrice/updatePriceRequest", output = "http://service.soap.ilia.ru/ServicePrice/updatePriceResponse")
    public boolean updatePrice(
        @WebParam(name = "arg0", partName = "arg0")
        Price arg0);

    /**
     * 
     * @return
     *     returns ru.ilia.soap.service.CustomError
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.soap.ilia.ru/ServicePrice/testErrorRequest", output = "http://service.soap.ilia.ru/ServicePrice/testErrorResponse")
    public CustomError testError();

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.service_shop.Price
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.soap.ilia.ru/ServicePrice/createPriceRequest", output = "http://service.soap.ilia.ru/ServicePrice/createPriceResponse")
    public Price createPrice(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.service_shop.PriceList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.soap.ilia.ru/ServicePrice/selectListRequest", output = "http://service.soap.ilia.ru/ServicePrice/selectListResponse")
    public PriceList selectList(
        @WebParam(name = "arg0", partName = "arg0")
        PriceListRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.service_shop.Price
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.soap.ilia.ru/ServicePrice/selectPriceRequest", output = "http://service.soap.ilia.ru/ServicePrice/selectPriceResponse")
    public Price selectPrice(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.soap.ilia.ru/ServicePrice/deletePriceRequest", output = "http://service.soap.ilia.ru/ServicePrice/deletePriceResponse")
    public boolean deletePrice(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

}
