
package ru.ilia.soap.impls;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicePriceImplService", targetNamespace = "http://impls.soap.ilia.ru/", wsdlLocation = "http://localhost:8080/priceWS?wsdl")
public class ServicePriceImplService
    extends Service
{

    private final static URL SERVICEPRICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEPRICEIMPLSERVICE_EXCEPTION;
    private final static QName SERVICEPRICEIMPLSERVICE_QNAME = new QName("http://impls.soap.ilia.ru/", "ServicePriceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/priceWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEPRICEIMPLSERVICE_WSDL_LOCATION = url;
        SERVICEPRICEIMPLSERVICE_EXCEPTION = e;
    }

    public ServicePriceImplService() {
        super(__getWsdlLocation(), SERVICEPRICEIMPLSERVICE_QNAME);
    }

    public ServicePriceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEPRICEIMPLSERVICE_QNAME, features);
    }

    public ServicePriceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEPRICEIMPLSERVICE_QNAME);
    }

    public ServicePriceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEPRICEIMPLSERVICE_QNAME, features);
    }

    public ServicePriceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicePriceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicePrice
     */
    @WebEndpoint(name = "ServicePriceImplPort")
    public ServicePrice getServicePriceImplPort() {
        return super.getPort(new QName("http://impls.soap.ilia.ru/", "ServicePriceImplPort"), ServicePrice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePrice
     */
    @WebEndpoint(name = "ServicePriceImplPort")
    public ServicePrice getServicePriceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impls.soap.ilia.ru/", "ServicePriceImplPort"), ServicePrice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEPRICEIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICEPRICEIMPLSERVICE_EXCEPTION;
        }
        return SERVICEPRICEIMPLSERVICE_WSDL_LOCATION;
    }

}
